#!/bin/bash
HTTPPORT=8000

# Exit the script if anything returns a non-zero value.
set -e

ls assets/styles/scss/*.scss assets/styles/scss/**/*.scss assets/styles/scss/**/**/*.scss assets/styles/scss/**/**/**/*.scss | ./watch - ./compilewatch &
if [ "$?" -ne 0 ]; then  
	echo "$(tput setaf 1)[start]$(tput sgr0) Watcher script for compass did not start or was not found."
else
	echo "$(tput setaf 2)[start]$(tput sgr0) Compass watcher process started."
fi


./watch assets/js/site.js uglifyjs assets/js/site.js -c -m -o assets/js/site.min.js &
if [ "$?" -ne 0 ]; then  
	echo "$(tput setaf 1)[start]$(tput sgr0) Watcher script for uglifyjs did not start or was not found."
else
	echo "$(tput setaf 2)[start]$(tput sgr0) uglifyjs watcher process started."
fi

livereloadx -s -p $HTTPPORT &
if [ "$?" -ne 0 ]; then  
	echo "$(tput setaf 1)[start]$(tput sgr0) Local web server reported an error and did not start, or was not found."
else
	echo "$(tput setaf 2)[start]$(tput sgr0) Local web server started on port $HTTPPORT."
fi
